
-- Sur Serveur 1
CREATE USER c##util1 IDENTIFIED BY util1;
GRANT CONNECT, RESOURCE TO c##util1;
ALTER USER c##util1 QUOTA 30M ON USERS;

-- Sur Serveur 2
CREATE USER c##util2 IDENTIFIED BY util2;
GRANT CONNECT, RESOURCE TO c##util2;
ALTER USER c##util2 QUOTA 30M ON USERS;